"""modes update

Revision ID: e356da9f43c0
Revises: 
Create Date: 2026-04-04 23:24:08.538918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e356da9f43c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_categories', sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False))
    op.add_column('transactions', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('category_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_owner_id'), 'transactions', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'transaction_categories', ['category_id'], ['id'])
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_owner_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_column('transactions', 'category_name')
    op.drop_column('transactions', 'category_id')
    op.drop_column('transactions', 'owner_id')
    op.drop_column('transaction_categories', 'type')
    # ### end Alembic commands ###
